#!/bin/sh

. /usr/local/lib/cont-init-functions.sh
ENSURE_DIR_MODE=2755
ENSURE_DIR_USER=aplus
ENSURE_DIR_GROUP=nogroup

ensure_dir /run/aplus
ensure_dir /local/aplus
ensure_dir /local/aplus/static
ensure_dir /local/aplus/media
